apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: example/nginx
    repoURL: 'https://github.com/ak9024/argocd.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
